//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiseFlag.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AddRequests = new HashSet<AddRequest>();
            this.Groups = new HashSet<Group>();
            this.OutOfRegionLogs = new HashSet<OutOfRegionLog>();
            this.UsersGroups = new HashSet<UsersGroup>();
            this.UsersLocations = new HashSet<UsersLocation>();
            this.UsersLocations1 = new HashSet<UsersLocation>();
        }
    
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HashedPassword { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Mobile { get; set; }
        public string EmergencyNo { get; set; }
        public string PassportID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedIP { get; set; }
        public string Pic { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string RememberToken { get; set; }
        public Nullable<System.DateTime> RememberTokenExpire { get; set; }
        public string DeviceToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddRequest> AddRequests { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutOfRegionLog> OutOfRegionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersGroup> UsersGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersLocation> UsersLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersLocation> UsersLocations1 { get; set; }
    }
}
