//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaiseFlag.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLocation
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long GroupID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Distance { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
